version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
      - ./web:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    networks:
      - frontend
    restart: always

networks:
  frontend:
